# Generated by Django 4.0.2 on 2022-07-27 04:05

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='email',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='end',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='start',
        ),
        migrations.AddField(
            model_name='queries',
            name='date',
            field=models.DateField(default=sqlalchemy.sql.expression.null),
        ),
    ]
