# Generated by Django 4.0.2 on 2022-07-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_queries_email_remove_queries_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='date',
            field=models.DateField(),
        ),
    ]
